//import {} from "https://raw.githubusercontent.com/omar-azmi/kitchensink_ts/main/src/mod.ts"
export { pack, packSeq, unpack, unpackSeq } from "./deps/raw.githubusercontent.com/omar-azmi/kitchensink_ts/main/src/eightpack.js"
export type { Decoded, JSPrimitive, PrimitiveArrayType, PrimitiveType } from "./deps/raw.githubusercontent.com/omar-azmi/kitchensink_ts/main/src/eightpack.js"
export { concatBytes } from "./deps/raw.githubusercontent.com/omar-azmi/kitchensink_ts/main/src/typedbuffer.js"
export type { ClassFieldsOf, ConstructorOf, NumericType, Require, VarNumericType } from "./deps/raw.githubusercontent.com/omar-azmi/kitchensink_ts/main/src/typedefs.js"
