//import {} from "https://raw.githubusercontent.com/omar-azmi/kitchensink_ts/main/src/mod.ts"
export { pack, packSeq, unpack, unpackSeq } from "https://deno.land/x/kitchensink_ts@v0.3.4/src/eightpack.ts"
export type { Decoded, JSPrimitive, PrimitiveArrayType, PrimitiveType } from "https://deno.land/x/kitchensink_ts@v0.3.4/src/eightpack.ts"
export { concatBytes } from "https://deno.land/x/kitchensink_ts@v0.3.4/src/typedbuffer.ts"
export type { ClassFieldsOf, ConstructorOf, NumericType, Require, VarNumericType } from "https://deno.land/x/kitchensink_ts@v0.3.4/src/typedefs.ts"
